### ISSUE TITLE
Is BUSL on SimulateSwap correct?

### ISSUE THREAD

**Issue by fp-crypto** [RageTrade/core#125]
https://github.com/rage-trade/perpswap-contracts/blob/dfce3fba59c4700ba7d03db72b8431ed4d32b1f7/contracts/libraries/SimulateSwap.sol#L1

 Is the intent for this to be released under BUSL? The libraries imported from uniswap are all GPLv2.

**Comment by 134dd3v** [comment]
SimulateSwap depends on [TickBitmapExtended](https://github.com/rage-trade/perpswap-contracts/blob/main/contracts/libraries/TickBitmapExtended.sol), which is a copy paste from Uniswap's repo with just a minor change required for SimulateSwap to work. Since [TickBitmap](https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/TickBitmap.sol) in Uniswap core is BUSL, the TickBitmapExtended has to inherit it and hence the SimulateSwap.

We'd like to have the most permissive license possible (as stated in the README in this repo), but we have to inherit the most restrictive license in the files. Any files in this repo which are BUSL they reference the [BUSL in Uniswap's code](https://github.com/Uniswap/v3-core/blob/main/LICENSE) and hence subject to it's terms.

**Comment by fp-crypto** [comment]
@134dd3v imo BUSL means that any contract that imports these libraries cannot be deployed to prod without Uniswap's permission. We should petition uniswap to relicense.
